# Generated by Django 4.1.7 on 2023-03-09 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], default='M', max_length=1)),
                ('date_visited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompleteBloodCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hb', models.DecimalField(decimal_places=2, max_digits=4)),
                ('platelets', models.DecimalField(decimal_places=2, max_digits=3)),
                ('tlc', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.patient')),
            ],
        ),
    ]
