# Generated by Django 4.1.7 on 2023-03-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_liverfunctiontest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completebloodcount',
            old_name='hb',
            new_name='haemoglobin',
        ),
        migrations.AddField(
            model_name='completebloodcount',
            name='basophils',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completebloodcount',
            name='eosinophils',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completebloodcount',
            name='hct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completebloodcount',
            name='lymph',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completebloodcount',
            name='lymphocytes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completebloodcount',
            name='mch',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completebloodcount',
            name='mchc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completebloodcount',
            name='mcv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completebloodcount',
            name='monocytes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completebloodcount',
            name='mpv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completebloodcount',
            name='neutrophils',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completebloodcount',
            name='pct',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completebloodcount',
            name='pdw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completebloodcount',
            name='rbc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completebloodcount',
            name='rdw_cv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
    ]
