# Generated by Django 4.1.7 on 2023-03-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_rename_hb_completebloodcount_haemoglobin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completebloodcount',
            name='hct',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='completebloodcount',
            name='mch',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='completebloodcount',
            name='mchc',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='completebloodcount',
            name='mcv',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='completebloodcount',
            name='mpv',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='completebloodcount',
            name='pdw',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='completebloodcount',
            name='rbc',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='completebloodcount',
            name='rdw_cv',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
