# Generated by Django 4.1.7 on 2023-03-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_alter_patient_date_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completebloodcount',
            name='basophils',
            field=models.CharField(default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='completebloodcount',
            name='eosinophils',
            field=models.CharField(default=None, max_length=2),
        ),
    ]
